# Generated by Django 6.0.2 on 2026-02-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_location_workhour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='Certified',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Pharmacy',
        ),
        migrations.AddField(
            model_name='statistics',
            name='working_hours',
            field=models.CharField(default='24/7', max_length=50, verbose_name='working hours'),
        ),
    ]
